config/routes.rb
Rails.application.routes.draw do
  resources :uploads

  get '/success' => 'uploads#success'
  get '/success/:id' => 'uploads#success'

  root 'uploads#new'

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  def cloud_big
    "http://res.cloudinary.com/dxdytksp9/image/upload/c_fit,fl_png8,h_2400,w_2400/v1428885019/#{cloudinary_code}.png"
  end

  def cloud_med
    "http://res.cloudinary.com/dxdytksp9/image/upload/c_fit,fl_png8,h_600,w_600/v1428885019/#{cloudinary_code}.png"
  end

  def url_1200

    "http://res.cloudinary.com/dxdytksp9/image/upload/c_scale,h_900,w_1200/c_fit,g_north,h_700,l_#{cloudinary_code},o_88,w_390,y_#{(140+((shirt_inches_from_top.to_f)*23)).to_i}/"
  end

  def url_small_mockup
    "http://res.cloudinary.com/dxdytksp9/image/upload/c_scale,w_575/c_fit,g_north,h_400,l_#{cloudinary_code},o_88,w_250,y_#{(94+((shirt_inches_from_top.to_f)*14)).to_i}/"
  end

  def url_big_mockup
    "http://res.cloudinary.com/dxdytksp9/image/upload/c_fit,g_north,h_1600,l_#{cloudinary_code},o_88,w_1000,y_#{(375+((shirt_inches_from_top.to_f)*56)).to_i}/"
  end


  def cloud_1200_mockup
    case shirt_color
    when "white"
      url_1200+"White-White_1200x900_qgkndw.jpg"
    when "black"
      url_1200+"Black-White_1200x900_wdpsbq.jpg"
    when "blue"
      url_1200+"Blue-White_1200x900_hdc8tp.jpg"
    when "green"
      url_1200+"Green-White_1200x900_p0uogb.jpg"
    when "orange"
      url_1200+"Orange-White_1200x900_vsox0a.jpg"
    when "pink"
      url_1200+"Pink-White_1200x900_i533je.jpg"
    when "purple"
      url_1200+"Purple-White_1200x900_vzurgu.jpg"
    when "red"
      url_1200+"Red-White_1200x900_r95swn.jpg"
    when "yellow"
      url_1200+"Yellow-White_1200x900_jp5rja.jpg"
    else
      url_1200+"White-White_1200x900_qgkndw.jpg"
    end
  end

  def cloud_1200_dark
    case shirt_color
    when "white"
      url_1200+"White-DarkTexture_1200x900_fyc6bq.jpg"
    when "black"
      url_1200+"Black-DarkTexture_1200x900_nkvzhe.jpg"
    when "blue"
      url_1200+"Blue-DarkTexture_1200x900_feqaau.jpg"
    when "green"
      url_1200+"Green-DarkTexture_1200x900_v4vepl.jpg"
    when "orange"
      url_1200+"Orange-DarkTexture_1200x900_fowiul.jpg"
    when "pink"
      url_1200+"Pink-DarkTexture_1200x900_lzaulh.jpg"
    when "purple"
      url_1200+"Purple-DarkTexture_1200x900_mhlkng.jpg"
    when "red"
      url_1200+"Red-DarkTexture_1200x900_xs6wkz.jpg"
    when "yellow"
      url_1200+"Yellow-DarkTexture_1200x900_s4b6ku.jpg"
    else
      url_1200+"White-DarkTexture_1200x900_fyc6bq.jpg"
    end
  end

  def cloud_1200_light
    case shirt_color
    when "white"
      url_1200+"White-LightTexture_1200x900_tk1qoi.jpg"
    when "black"
      url_1200+"Black-LightTexture_1200x900_x6spef.jpg"
    when "blue"
      url_1200+"Blue-LightTexture_1200x900_obrlw9.jpg"
    when "green"
      url_1200+"Green-LightTexture_1200x900_itd690.jpg"
    when "orange"
      url_1200+"Orange-LightTexture_1200x900_krpu2r.jpg"
    when "pink"
      url_1200+"Pink-LightTexture_1200x900_peppnw.jpg"
    when "purple"
      url_1200+"Purple-LightTexture_1200x900_pzygzj.jpg"
    when "red"
      url_1200+"Red-LightTexture_1200x900_ebgtw8.jpg"
    when "yellow"
      url_1200+"Yellow-LightTexture_1200x900_q6c57w.jpg"
    else
      url_1200+"White-LightTexture_1200x900_tk1qoi.jpg"
    end
  end


  def cloud_small_mockup
    case shirt_color
    when "white"
      url_small_mockup+"White-Transparent_2300x2415_ecwmqc.jpg"
    when "black"
      url_small_mockup+"Black-Transparent_2300x2415_m6fd3w.jpg"
    when "blue"
      url_small_mockup+"Blue-Transparent_2300x2415_kxvgkd.jpg"
    when "green"
      url_small_mockup+"Green-Transparent_2300x2415_qkw0ta.jpg"
    when "orange"
      url_small_mockup+"Orange-Transparent_2300x2415_ztzgv6.jpg"
    when "pink"
      url_small_mockup+"Pink-Transparent_2300x2415_tcxwet.jpg"
    when "purple"
      url_small_mockup+"Purple-Transparent_2300x2415_y5yv8p.jpg"
    when "red"
      url_small_mockup+"Red-Transparent_2300x2415_wexfhx.jpg"
    when "yellow"
      url_small_mockup+"Yellow-Transparent_2300x2415_bz2vss.jpg"
    else
      url_small_mockup+"White-White_1200x900_qgkndw.jpg"
    end
  end

  def cloud_big_mockup
    case shirt_color
    when "white"
      url_big_mockup+"White-Transparent_2300x2415_ecwmqc.jpg"
    when "black"
      url_big_mockup+"Black-Transparent_2300x2415_m6fd3w.jpg"
    when "blue"
      url_big_mockup+"Blue-Transparent_2300x2415_kxvgkd.jpg"
    when "green"
      url_big_mockup+"Green-Transparent_2300x2415_qkw0ta.jpg"
    when "orange"
      url_big_mockup+"Orange-Transparent_2300x2415_ztzgv6.jpg"
    when "pink"
      url_big_mockup+"Pink-Transparent_2300x2415_tcxwet.jpg"
    when "purple"
      url_big_mockup+"Purple-Transparent_2300x2415_y5yv8p.jpg"
    when "red"
      url_big_mockup+"Red-Transparent_2300x2415_wexfhx.jpg"
    when "yellow"
      url_big_mockup+"Yellow-Transparent_2300x2415_bz2vss.jpg"
    else
      url_big_mockup+"White-White_1200x900_qgkndw.jpg"
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_http_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == "tone" && password == "musictshirts1"
    end
  end



end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]
  before_action :require_http_auth, only: [:index]

  protect_from_forgery :except => :create

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    puts params[:image]
    cloudinary = Cloudinary::Uploader.upload(params[:image])
    @upload = Upload.new
    @upload.cloudinary_code = cloudinary["public_id"]
    @upload.height = cloudinary["height"]
    @upload.width = cloudinary["width"]

    @upload.shirt_inches_from_top = params[:inches]
    @upload.shirt_color = params[:color]
    @upload.shirt_name = params[:shirt_name]
    @upload.band_name = params[:band_name]
    @upload.bancamp_url = params[:bancamp_url]
    @upload.user_email = params[:email]
    @upload.user_fullname = params[:full_name]
    @upload.paypal_email = params[:paypal_email]
    



    Stripe.api_key = ENV['SECRET_KEY']

    # Get the credit card details submitted by the form
    token = params[:stripeToken]

    # Create a Customer
    customer = Stripe::Customer.create(
      :source => token,
      :description => params[:email]
    )
    @upload.stripe_customer_id = customer.id
    respond_to do |format|
      if @upload.save
        GeneralMailer.email(params[:email],
        "Your T-Shirt Has Been Created!",
        @upload).deliver
        format.html { redirect_to "/success/#{@upload.id}", mockup: @upload.cloud_small_mockup, notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params[:upload]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToneThreads</title>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["PUBLISHABLE_KEY"] %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://tonethreads.com/favicon.ico" rel="shortcut icon">

</head>
<body>
  <div id="header">
    <a href="/"><%=image_tag 'tonethreadslogo.png' %></a> <a class="learn" target="_blank" href="http://tonethreads.com/info"><i class="fa fa-info-circle fa-2x"></i></a>
  </div>
  <%= yield %>
  <footer>
    © 2015 ToneThreads
    <a href="http://tonethreads.com/about">About</a>
    <a href="http://tonethreads.com/faq">FAQ</a>
    <a href="http://tonethreads.com/privacy">Privacy</a>
    <a href="http://tonethreads.com/terms">Terms</a>
  </footer>
</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :paypal_email %><br />
    <%= f.text_field :paypal_email  %>


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<div class="index">
  <h1>Shirt uploads</h1>

  <table>
    <thead>
      <tr>
        <th>email</th>
        <th>user full name</th>
        <th>color</th>
        <th>shirt name</th>
        <th>inches</th>
        <th>bane name</th>
        <th>bandcamp url</th>
        <th>stripe_customer_id</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @uploads.each do |upload| %>
        <tr>
          <td><%= upload.user_email %></td>
          <td><%= upload.user_fullname %></td>
          <td><%= upload.shirt_color %></td>
          <td><%= upload.shirt_name %></td>
          <td><%= upload.shirt_inches_from_top %></td>
          <td><%= upload.band_name %></td>
          <td><%= upload.bancamp_url %></td>
          <td><%= upload.stripe_customer_id %></td>
          <td><%= link_to "white", upload.cloud_1200_mockup %></td>
          <td><%= link_to "dark", upload.cloud_1200_dark %></td>
          <td><%= link_to "light", upload.cloud_1200_light %></td>

          <td><%= link_to "medium mockup", upload.cloud_small_mockup %></td>
          <td><%= link_to "large mockup", upload.cloud_big_mockup %></td>
          <td><%= link_to "full source", upload.cloud_big %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Upload', new_upload_path %>
</div>

app/views/uploads/new.html.erb
<div id="container" class="container"></div>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/success.html.erb
<div class="success">
  <h1>Success! Your t-shirt has been created.</h1>
  <h2>You will be receiving an email shortly with further instructions.</h2>
  <% if params[:id] %>
    <%= image_tag Upload.find(params[:id]).cloud_small_mockup %>
  <% end %>
</div>